/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-03-09 17:21:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"js/view/jquery/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/popper/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("  <title>Registration</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" align=\"center\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h2>Registration</h2>\r\n");
      out.write("\t\t<img class=\"mb-4\" src=\"icon/regIcon.svg\" alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h3>Enter your details:</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("  \t\t<form action=\"/WebGymTracking/GymTrackingController\" method=\"post\">\r\n");
      out.write("  \t\t<h4 style=\"color:red; font-weight:bold;\">");
if(request.getAttribute("message") != null)
            out.write((String)request.getAttribute("message")); 
      out.write("</h4>\r\n");
      out.write("\t  \t<input type=\"hidden\" name=\"command\" value=\"registration\">\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  \t");
      out.write("\r\n");
      out.write("\t  \t<div class=\"form-group\">\r\n");
      out.write("\t  \t\t<label for=\"userName\">Username:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"userName\" placeholder=\"Enter username\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t  \t");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"password\">Password:</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter password\">\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("         \t<label for=\"rePassword\">Re-Password:</label>\r\n");
      out.write("         \t<input type=\"password\" class=\"form-control\" name=\"rePassword\" placeholder=\"Enter password\">\r\n");
      out.write("         </div>\r\n");
      out.write("          \r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("         \t<label for=\"weight\">Weight:</label>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("             \t<input type=\"number\" size=\"3\" step=\"1\" min=\"30\" max=\"150\" placeholder=\"90\" id=\"inputWeight\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<input type=\"range\" id=\"sliderWeight\" class=\"custom-range\" name=\"weight\" value=\"90\" min=\"30\" max=\"150\" />\r\n");
      out.write("         </div>\r\n");
      out.write("            \r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("        \t<label for=\"height\">Height:</label>\r\n");
      out.write("          \t<div align=\"center\">\r\n");
      out.write("             \t<input type=\"number\" size=\"3\" step=\"1\" min=\"100\" max=\"250\" placeholder=\"150\" id=\"inputHeight\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"range\" id=\"sliderHeight\" class=\"custom-range\" name=\"height\" value=\"150\" min=\"100\" max=\"250\" />\r\n");
      out.write("          </div>\r\n");
      out.write("         \t          \r\n");
      out.write("          <input type=\"submit\" class=\"btn btn-outline-warning\" name=\"command\" value=\"registration\" ><br>\r\n");
      out.write("          <a href=\"login.jsp\" class=\"badge badge-light\" role=\"button\" aria-pressed=\"true\">Back to login</a><br>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    var sliderWeight = document.getElementById(\"sliderWeight\");\r\n");
      out.write("    var sliderHeight = document.getElementById(\"sliderHeight\");\r\n");
      out.write("    var inputWeight = document.getElementById(\"inputWeight\");\r\n");
      out.write("    var inputHeight = document.getElementById(\"inputHeight\");\r\n");
      out.write("\r\n");
      out.write("    ///value updation from input to slider\r\n");
      out.write("    //function input update to slider\r\n");
      out.write("    function sliderWeightInput(){//input udate slider Weight\r\n");
      out.write("    \tsliderWeight.value = inputWeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    function sliderHeightInput(){//input update slider Height\r\n");
      out.write("    \tsliderHeight.value = (inputHeight.value);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //calling function on change of inputs to update in slider\r\n");
      out.write("    inputWeight.addEventListener(\"change\",sliderWeightInput);\r\n");
      out.write("    inputHeight.addEventListener(\"change\",sliderHeightInput);\r\n");
      out.write("\r\n");
      out.write("    ///value updation from slider to input\r\n");
      out.write("    //functions to update from slider to inputs \r\n");
      out.write("    function inputWeightSliderWeight(){//slider update inputs\r\n");
      out.write("       inputWeight.value = sliderWeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    function inputHeightSliderHeight(){//slider update inputs\r\n");
      out.write("       inputHeight.value = sliderHeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    sliderWeight.addEventListener(\"change\",inputWeightSliderWeight);\r\n");
      out.write("    sliderHeight.addEventListener(\"change\",inputHeightSliderHeight);\r\n");
      out.write("    </script>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
