/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-03-09 17:12:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hit.model.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hit.model");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"js/view/jquery/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/popper/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("  <title>Search</title>\r\n");
      out.write("  <style>\r\n");
      out.write("  h4{\r\n");
      out.write("  color:red\r\n");
      out.write("  }\r\n");
      out.write("  em {\r\n");
      out.write("  font-style: normal;         /* Removes italics */\r\n");
      out.write("  text-decoration: underline; /* Makes underline */\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-dark bg-dark\">\r\n");
      out.write("\t<img src=\"icon/navbarIcon.svg\" width=\"30\" height=\"30\" class=\"d-inline-block align-top\" alt=\"\"><h3 style=\"color:white;\">GymTracking</h3>\r\n");
      out.write("  \t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"true\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  \t</button>\r\n");
      out.write("  \t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("   \t\t<ul class=\"navbar-nav\">\r\n");
      out.write("      \t\t<li class=\"nav-item active\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"userMain.jsp\">Home<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"userActivities.jsp\">MyActivity</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"search.jsp\">Search</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("       \t\t\t<a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("        \t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t");
User user = (User)session.getAttribute("loginUser");
          		out.println(user.getUserName()); 
      out.write("\r\n");
      out.write("        \t\t</a>\r\n");
      out.write("        \t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updateUser.jsp\">Update User</a>\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updateWeightAndHeight.jsp\">Update Weight And Height</a>\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updatePassword.jsp\">Update Password</a>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<form action=\"/WebGymTracking/GymTrackingController\" method=\"get\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"command\" value=\"logout\" >\r\n");
      out.write("            \t<input class=\"btn btn-danger\" type=\"submit\" value=\"logout\">\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<img class=\"mb-4\" src=\"icon/iconSearch.svg\" alt=\"\" width=\"72\" height=\"72\"><br>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<h4><em>Back</em></h4>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#DeadliftWithRod\">Deadlift with rod</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#NarrowRowingInTheMachine\">Narrow rowing in the machine</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#HorizontalBar\">Horizontal bar</button><br><br>\r\n");
      out.write("\t<h4><em>Shoulders</em></h4><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#AStandingShoulderPressWithARod\">A standing shoulder press with a rod</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#AShrugOfTheShouldersWithWeights\">A shrug of the shoulders with weights</button><br><br>\r\n");
      out.write("\t<h4><em>Chest</em></h4><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#BenchPress\">Bench press</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#BreastButterflyWithWeights\">Breast butterfly with weights</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#Pushups\">Pushups</button><br><br>\r\n");
      out.write("\t<h4><em>Hands</em></h4><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#BendingTheElbowsWithStandingRod\">Bending the elbows with standing rod</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#One-ArmDumbbellRow\">One-Arm Dumbbell Row</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#KickBack\">Kick Back</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#PullingElbowsInSittingWithWeights\">Pulling elbows in sitting with weights</button><br><br>\r\n");
      out.write("\t<h4><em>Stomach</em></h4><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#StaticStomachPlank\">Static stomach/Plank</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#Crunches\">Crunches</button><br><br>\r\n");
      out.write("\t<h4><em>Legs</em></h4><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#Deadlift\">Deadlift</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#Squat\">Squat</button><br><br>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-light text-dark\" data-toggle=\"modal\" data-target=\"#Foot-pressingExerciseAgainstAMachine\">Foot-pressing exercise against a machine</button><br><br>\r\n");
      out.write("\t<a href=\"userMain.jsp\" class=\"badge badge-info\" role=\"button\" aria-pressed=\"true\">Back to Main</a>     \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"DeadliftWithRod\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"DeadliftWithRod\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"DeadliftWithRod\">Deadlift with rod</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        Deadlift is a weight training exercise in which an Olympic pole is lifted from \r\n");
      out.write("        the floor in a position where the legs are bent and the back straight. \r\n");
      out.write("        Deadlift is a complex exercise that improves the grip of the hands, and works mainly on the muscles of the \r\n");
      out.write("        back of the back,the large buttock muscle, the large mitochondrial muscle, the muscles of the hamstring,\r\n");
      out.write("        the quadriceps and the soles of the sole.\r\n");
      out.write("        <br> <br> <b> Tip: </b>  1 set of 5 reps once a week.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"NarrowRowingInTheMachine\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"NarrowRowingInTheMachine\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"NarrowRowingInTheMachine\">Narrow rowing in the machine</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      One of the base exercises whose primary purpose is to work on the broad top (Latissimus Dorsi).\r\n");
      out.write("      The rowing begins and ends on the floor at each repetition [like deadlift]\r\n");
      out.write("      and does not end when the weight is suspended in the air with the hands straight.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 6-1 high intensity repetitions, with 3-5 minutes rest between the sets.\r\n");
      out.write("      <br> <b> Note: </b>Stretching is recommended at the end of the exercise.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"HorizontalBar\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"HorizontalBar\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"HorizontalBar\">Horizontal bar</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      Stress is a fitness facility consisting of a horizontal bar that is far from the ground.\r\n");
      out.write("      The purpose of the facility is to allow the user to hang on it and lift it with his help,\r\n");
      out.write("      while activating the muscles of the hands, back and abdomen.\r\n");
      out.write("      The accepted style of tension is to hang on to it while holding on to \r\n");
      out.write("      the hands and without touching the ground,and making ups and downs without the legs' help, so that \r\n");
      out.write("      the chin's lift passes the rod, and the descent is up to the alignment of the hands.\r\n");
      out.write("      <br> <br> <b> Tip:</b> 3 sets of 6 reps with a minute to 2 minutes rest with maximum weight.\r\n");
      out.write("      <br> <b>Perform 6 repetitions of tension and feel easy for you? </b> \r\n");
      out.write("      <br>Add weight in the form of a handweight between your legs.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"AStandingShoulderPressWithARod\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"AStandingShoulderPressWithARod\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"AStandingShoulderPressWithARod\">A standing shoulder press with a rod</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      A shoulder press is designed for deep work on the front and middle heads of the delta muscle.\r\n");
      out.write("      Through it you increase the mass and strength of all the muscles around the shoulder joint.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 2-4 sets of 7-12 repetitions.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"AShrugOfTheShouldersWithWeights\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"AShrugOfTheShouldersWithWeights\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"AShrugOfTheShouldersWithWeights\">A shrug of the shoulders with weights</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      A shoulder press is designed for deep work on the front and middle heads of the delta muscle.\r\n");
      out.write("      Through it you increase the mass and strength of all the muscles around the shoulder joint.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 2-4 sets of 7-12 repetitions.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"BenchPress\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"BenchPress\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"BenchPress\">Bench press</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      The bench press is a great exercise for anyone looking to gain muscle size and strength in the upper body.\r\n");
      out.write("      This exercise is known as a compound exercise, meaning it involves multiple joints, and therefore \r\n");
      out.write("      multiple major muscle groups to execute.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 3-5 sets of 7-12 repetitions.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"BreastButterflyWithWeights\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"BreastButterflyWithWeights\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"BreastButterflyWithWeights\">Breast butterfly with weights</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      A breast butterfly in the machine is an effective exercise to sharpen the chest muscles.\r\n");
      out.write("      Exercise contributes to the chest appearance \"rough\".\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 3-4 sets of 8-15 repetitions. \r\n");
      out.write("      <br>Before that, regular breast training should be performed. \r\n");
      out.write("      <br>The exercise is suitable for trainees at all levels.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"Pushups\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Pushups\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"Pushups\">Pushups</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      Push-ups is a physical exercise exercise, based on applying the entire body's strength to the elbows and legs.\r\n");
      out.write("      The gymnast straightens his elbows while pushing the body upwards.Push-ups are designed to strengthen \r\n");
      out.write("      the muscles of the hands (triceps), back, shoulder (delta muscle) and chest (large chest muscle).\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 3 sets of 15 repetitions. rest of 30-60 seconds between each set.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"BendingTheElbowsWithStandingRod\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"BendingTheElbowsWithStandingRod\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"BendingTheElbowsWithStandingRod\">Bending the elbows with standing rod</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      his exercise works on the biceps of the hand. The muscle participates in all \r\n");
      out.write("      movements that combine hand-pulling towards the body. \r\n");
      out.write("      In addition, this is the most effective exercise toincrease the strength and volume of the hand.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  2-3 set of 8-12 reps.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"One-ArmDumbbellRow\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"One-ArmDumbbellRow\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"One-ArmDumbbellRow\">One-Arm Dumbbell Row</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      his exercise targets the upper and lower back, shoulders, biceps, and hips while improving core stability.\r\n");
      out.write("      Five different joint actions take place in this compound exercise.Beginners can use light weights as they build strength.\r\n");
      out.write("      This is also a good exercise to do as part of a circuit training routine.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  2-3 set of 8-12 reps.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"KickBack\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"KickBack\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"KickBack\">Kick Back</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      Purpose of the exercise: Strengthening The triceps muscle (the back of the arm). \r\n");
      out.write("      The rear hand muscle is a very large muscle in the hand and it assembles most of the hand mass.\r\n");
      out.write("      It is located at the back of the hand and is responsible for the movement of the elbow alignment.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  3 set of 20 reps once a week.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"PullingElbowsInSittingWithWeights\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"PullingElbowsInSittingWithWeights\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"PullingElbowsInSittingWithWeights\">Pulling elbows in sitting with weights</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      The best aim of the exercise is tosharpen it and  increase the strength of the biceps muscle.\r\n");
      out.write("      Full shoulder flexion should beallowed to allow full hand pulling. It should be noted that the brace \r\n");
      out.write("      (if any) will not be too high and will prevent the weight of the hand from being fully lowered.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  3-4 set of 8-12 reps once a week.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"StaticStomachPlank\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"StaticStomachPlank\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"StaticStomachPlank\">Static stomach/Plank</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      A static stomach is a power exercise that involves staying in a static position. \r\n");
      out.write("      The most common plank is a front plank, which stays in a push-up position when the body weight is carried on the arms, elbows and toes.\r\n");
      out.write("      The plank strengthens the abdominal muscles, back and shoulders.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 4 sets. 60 seconds in the first set, 50 seconds in the second, 40 seconds in the third, \r\n");
      out.write("      30 seconds in the fourth. rest of 45 seconds between each set.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"Crunches\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Crunches\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"Crunches\">Crunches</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      Crunches is a physical exercise exercise, based on activating the mass of the upper body on the abdominal muscle.\r\n");
      out.write("      Crunches are designed to strengthenthe abdominal muscles. Exercise is one of the popular \r\n");
      out.write("      exercises because it can be done anywhere and without special equipment.\r\n");
      out.write("      <br> <br> <b> Tip:</b> Perform 55 sets of 40 repetitions. rest of 30-60 seconds between each set.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"Deadlift\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Deadlift\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"Deadlift\">Deadlift</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      Deadlift is a weight training exercise in which an Olympic pole is lifted from the floor in a position where the legs \r\n");
      out.write("      are bent and the back straight.Deadlift is a complex exercise that improves the grip of the hands, and \r\n");
      out.write("      works mainly on the muscles of the back of the back, the large buttock muscle, the large mitochondrial muscle, \r\n");
      out.write("      the muscles of the hamstring, the quadriceps and the soles of the sole.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  1 set of 5 reps once a week.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"Squat\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Squat\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"Squat\">Squat</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      A squat is a complex multi-joint exercise that, when performed, activates the ankle joint, knee, and thigh.\r\n");
      out.write("      As a result of this activity, the body mobilizes a large number of muscles, in fact, almost all \r\n");
      out.write("      the muscles in the body . The exercise shapes the muscles of the legs and buttocks.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  4 set of 6 reps.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"Foot-pressingExerciseAgainstAMachine\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Foot-pressingExerciseAgainstAMachine\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"Foot-pressingExerciseAgainstAMachine\">Foot-pressing exercise against a machine</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      The exercise is performed using power machines. In this exercise there are three agonists, the buttocks, the quadriceps and \r\n");
      out.write("      the sinus muscles, and three joints  involved in the exercise,the hip joint, the knee joint, and the ankle joint.\r\n");
      out.write("      <br> <br> <b> Tip: </b>  4 set of 15 reps.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <a class=\"btn btn-primary\" href=\"addActive.jsp\" role=\"button\">Add Active</a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
