/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-03-09 17:04:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hit.model.*;

public final class updateUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hit.model");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"js/view/jquery/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/popper/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/view/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/sliderUser.js\"></script>\r\n");
      out.write("  <title>Update User</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-dark bg-dark\">\r\n");
      out.write("\t<img src=\"icon/navbarIcon.svg\" width=\"30\" height=\"30\" class=\"d-inline-block align-top\" alt=\"\"><h3 style=\"color:white;\">GymTracking</h3>\r\n");
      out.write("  \t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"true\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  \t</button>\r\n");
      out.write("  \t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("   \t\t<ul class=\"navbar-nav\">\r\n");
      out.write("      \t\t<li class=\"nav-item active\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"userMain.jsp\">Home<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"userActivities.jsp\">MyActivity</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<a class=\"nav-link\" href=\"search.jsp\">Search</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("       \t\t\t<a class=\"nav-link\" href=\"about.jsp\">About</a>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("        \t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          \t\t");
User user = (User)session.getAttribute("loginUser");
          		out.println(user.getUserName()); 
      out.write("\r\n");
      out.write("        \t\t</a>\r\n");
      out.write("        \t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updateUser.jsp\">Update User</a>\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updateWeightAndHeight.jsp\">Update Weight And Height</a>\r\n");
      out.write("          \t\t<a class=\"dropdown-item\" href=\"updatePassword.jsp\">Update Password</a>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("      \t\t<li class=\"nav-item\">\r\n");
      out.write("        \t\t<form action=\"/WebGymTracking/GymTrackingController\" method=\"get\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"command\" value=\"logout\" >\r\n");
      out.write("            \t<input class=\"btn btn-danger\" type=\"submit\" value=\"logout\">\r\n");
      out.write("        \t\t</form>\r\n");
      out.write("      \t\t</li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  \t<h2>Please update your information:</h2>\r\n");
      out.write("  \t");
      out.write("\r\n");
      out.write("  \t<form action=\"/WebGymTracking/GymTrackingController\" method=\"post\">\r\n");
      out.write("  \t");

  	int valueWeight = user.getWeight();//The weight of the user
  	int valueHeight = user.getHeight();//The height of the user
  	
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \t<h4 style=\"color:red; font-weight:bold;\">");
if(request.getAttribute("message") != null)
		out.write((String)request.getAttribute("message")); 
      out.write("</h4>\r\n");
      out.write("\t<input type=\"hidden\" name=\"command\" value=\"updateUser\"> \r\n");
      out.write("\t\r\n");
      out.write("\t   \t");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"password\">Old Password:</label>\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" name=\"oldPassword\" placeholder=\"Enter your old password\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"newPassword\">New Password:</label>\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" name=\"newPassword\" placeholder=\"Enter your new password\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"rePassword\">Re-Password:</label>\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" name=\"rePassword\" placeholder=\"Re-enter your new password\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("          \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"weight\">Weight:</label>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("            \t<input type=\"number\" size=\"2\" step=\"1\" min=\"30\" max=\"150\" placeholder=\"");
      out.print( valueWeight );
      out.write("\" id=\"inputWeight\" >\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<input type=\"range\" id=\"sliderWeight\" class=\"custom-range\" name=\"newWeight\" value=\"");
      out.print( valueWeight );
      out.write("\" min=\"30\" max=\"150\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("        \t<label for=\"height\">Height:</label>\r\n");
      out.write("        \t<div align=\"center\">\r\n");
      out.write("            \t<input type=\"number\" size=\"2\" step=\"1\" min=\"100\" max=\"250\" placeholder=\"");
      out.print( valueHeight );
      out.write("\" id=\"inputHeight\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"range\" id=\"sliderHeight\" class=\"custom-range\" name=\"newHeight\" value=\"");
      out.print( valueHeight );
      out.write("\" min=\"100\" max=\"250\" />\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"btn btn-light\" name=\"command\" value=\"updateUser\" ><br>\r\n");
      out.write("            <a href=\"userMain.jsp\" class=\"badge badge-info\" role=\"button\" aria-pressed=\"true\">Back to Main</a>     \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    var sliderWeight = document.getElementById(\"sliderWeight\");\r\n");
      out.write("    var sliderHeight = document.getElementById(\"sliderHeight\");\r\n");
      out.write("    var inputWeight = document.getElementById(\"inputWeight\");\r\n");
      out.write("    var inputHeight = document.getElementById(\"inputHeight\");\r\n");
      out.write("\r\n");
      out.write("    ///value updation from input to slider\r\n");
      out.write("    //function input update to slider\r\n");
      out.write("    function sliderWeightInput(){//input udate slider Weight\r\n");
      out.write("    \tsliderWeight.value = inputWeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    function sliderHeightInput(){//input update slider Height\r\n");
      out.write("    \tsliderHeight.value = (inputHeight.value);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //calling function on change of inputs to update in slider\r\n");
      out.write("    inputWeight.addEventListener(\"change\",sliderWeightInput);\r\n");
      out.write("    inputHeight.addEventListener(\"change\",sliderHeightInput);\r\n");
      out.write("\r\n");
      out.write("    ///value updation from slider to input\r\n");
      out.write("    //functions to update from slider to inputs \r\n");
      out.write("    function inputWeightSliderWeight(){//slider update inputs\r\n");
      out.write("       inputWeight.value = sliderWeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    function inputHeightSliderHeight(){//slider update inputs\r\n");
      out.write("       inputHeight.value = sliderHeight.value;\r\n");
      out.write("    }\r\n");
      out.write("    sliderWeight.addEventListener(\"change\",inputWeightSliderWeight);\r\n");
      out.write("    sliderHeight.addEventListener(\"change\",inputHeightSliderHeight);\r\n");
      out.write("    </script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
